### ISSUE TITLE
Could not find package msgu. Updating recipe repos...

### ISSUE THREAD

**Issue by hkjels** [emacs-vs/ts-docstr#5]
I get the error "Could not find package msgu. Updating recipe repos..." when trying to install. The same error is returned after running `straight-pull-recipe-repositories` and re-trying as well.

**Comment by jcs090218** [comment]
It's not on GNU ELPA or MELPA. The package link is https://github.com/jcs-elpa/msgu. You can consider add JCS-ELPA to your package.el.
